#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from teste.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "teste.y"

#include <ctype.h>
#include <regex.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void yyerror(const char *s);
int yylex(void);

typedef enum { 
    TIPO_NUMERO, 
    TIPO_CADEIA 
} TipoValor;

typedef struct Variavel {
    char *tipo;
    char *nome;
    TipoValor tipo_valor;
    union {
        int num_valor;
        char *str_valor;
    } valor;
    char *tipo_linha;
    struct Variavel *proximo;
} Variavel;

typedef struct Escopo {
    Variavel *variaveis;
    struct Escopo *proximo;
} Escopo;

Escopo *pilha_de_escopos = NULL;

void empilhar_escopo() {
    Escopo *novo_escopo = (Escopo *)malloc(sizeof(Escopo));
    novo_escopo->variaveis = NULL;
    novo_escopo->proximo = pilha_de_escopos;
    pilha_de_escopos = novo_escopo;
}

void desempilhar_escopo() {
    if (pilha_de_escopos != NULL) {
        Escopo *escopo_antigo = pilha_de_escopos;
        pilha_de_escopos = pilha_de_escopos->proximo;
        free(escopo_antigo);
    } else {
        printf("Erro: tentativa de remover escopo inexistente\n");
    }
}

void inicializar_pilha_de_escopos() {
    pilha_de_escopos = NULL;
}

Variavel* verifica_variavel_existe_pilha(char *identificador) {
    Escopo *escopo_atual = pilha_de_escopos;
    while (escopo_atual != NULL) {
        Variavel *var_atual = escopo_atual->variaveis;
        while (var_atual != NULL) {
            if (strcmp(var_atual->nome, identificador) == 0) {
                return var_atual;
            }
            var_atual = var_atual->proximo;
        }
        escopo_atual = escopo_atual->proximo;
    }
    return NULL;
}

Variavel* verifica_variavel_existe_escopo_atual(char *identificador) {
    if (pilha_de_escopos == NULL) {
        return NULL;
    }

    Variavel *var_atual = pilha_de_escopos->variaveis;
    while (var_atual != NULL) {
        if (strcmp(var_atual->nome, identificador) == 0) {
            return var_atual;
        }
        var_atual = var_atual->proximo;
    }

    return NULL;
}

char* verifica_tipo_variavel(char *nome_var) {
    Escopo *escopo_atual = pilha_de_escopos;
    while (escopo_atual != NULL) {
        Variavel *var_atual = escopo_atual->variaveis;
        while (var_atual != NULL) {
            if (strcmp(var_atual->nome, nome_var) == 0) {
                return var_atual->tipo;
            }
            var_atual = var_atual->proximo;
        }
        escopo_atual = escopo_atual->proximo;
    }
    printf("Erro: variável %s não encontrada\n", nome_var);
    return NULL; // Retornar NULL se a variável não for encontrada
}

int busca_valor_variavel_numero(char *nome_var) {
    Escopo *escopo_atual = pilha_de_escopos;
    while (escopo_atual != NULL) {
        Variavel *var_atual = escopo_atual->variaveis;
        while (var_atual != NULL) {
            if (strcmp(var_atual->nome, nome_var) == 0) {
                if (var_atual->tipo_valor == TIPO_NUMERO) {
                    return var_atual->valor.num_valor;
                } else {
                    printf("Erro: variável %s não é do tipo NUMERO\n", nome_var);
                    return 0; // Valor padrão ou tratar erro de outra forma
                }
            }
            var_atual = var_atual->proximo;
        }
        escopo_atual = escopo_atual->proximo;
    }
    printf("Erro: variável %s não encontrada\n", nome_var);
    return 0; // Valor padrão se a variável não for encontrada
}

char* busca_valor_variavel_cadeia(char *nome_var) {
    Escopo *escopo_atual = pilha_de_escopos;
    while (escopo_atual != NULL) {
        Variavel *var_atual = escopo_atual->variaveis;
        while (var_atual != NULL) {
            if (strcmp(var_atual->nome, nome_var) == 0) {
                if (var_atual->tipo_valor == TIPO_CADEIA) {
                    return var_atual->valor.str_valor;
                } else {
                    printf("Erro: variável %s não é do tipo CADEIA\n", nome_var);
                    return NULL; // Valor padrão ou tratar erro de outra forma
                }
            }
            var_atual = var_atual->proximo;
        }
        escopo_atual = escopo_atual->proximo;
    }
    printf("Erro: variável %s não encontrada\n", nome_var);
    return NULL; // Valor padrão se a variável não for encontrada
}

char* buscar_tipo_linha(char *nome_variavel) {
    Escopo *escopo_atual = pilha_de_escopos;
    while (escopo_atual != NULL) {
        Variavel *var_atual = escopo_atual->variaveis;
        while (var_atual != NULL) {
            if (strcmp(var_atual->nome, nome_variavel) == 0) {
                return var_atual->tipo_linha;
            }
            var_atual = var_atual->proximo;
        }
        escopo_atual = escopo_atual->proximo;
    }
    return NULL; // Retorna NULL se a variável não for encontrada
}

char* remove_espacos(const char* str) {
    int i, j;
    int len = strlen(str);
    char* nova_str = (char*)malloc(len + 1); // Aloca memória para a nova string

    if (nova_str == NULL) {
        fprintf(stderr, "Erro de alocação de memória\n");
        exit(1);
    }

    for (i = 0, j = 0; i < len; i++) {
        if (str[i] != ' ') {
            nova_str[j++] = str[i];
        }
    }
    nova_str[j] = '\0'; // Termina a nova string

    return nova_str;
}


char* remove_espacos_fora_aspas( char* str) {
    int len = strlen(str);
    char* nova_str = (char*)malloc(len + 1); // Aloca memória para a nova string
    if (nova_str == NULL) {
        fprintf(stderr, "Erro de alocação de memória\n");
        exit(1);
    }

    int i, j = 0;
    int dentro_aspas = 0; // Flag para rastrear se estamos dentro de aspas

    for (i = 0; i < len; i++) {
        if (str[i] == '"') {
            dentro_aspas = !dentro_aspas; // Alterna o estado dentro/fora de aspas
        }

        if (dentro_aspas || (!dentro_aspas && str[i] != ' ')) {
            nova_str[j++] = str[i];
        }
    }
    nova_str[j] = '\0'; // Termina a nova string

    return nova_str;
}

void adicionar_variavel_numero(char *tipo, char *nome, int num_valor, char *tipo_linha) {
    if (pilha_de_escopos == NULL) {
        printf("Erro: pilha de escopos não inicializada\n");
        return;
    }
    Variavel *nova_variavel = (Variavel *)malloc(sizeof(Variavel));
    nova_variavel->tipo = strdup(tipo);
    nova_variavel->nome = strdup(nome);
    nova_variavel->tipo_valor = TIPO_NUMERO;
    nova_variavel->valor.num_valor = num_valor;

    nova_variavel->tipo_linha = tipo_linha;

    nova_variavel->proximo = pilha_de_escopos->variaveis;
    pilha_de_escopos->variaveis = nova_variavel;
}

void adicionar_variavel_cadeia(char *tipo, char *nome, char *str_valor, char *tipo_linha) {
    if (pilha_de_escopos == NULL) {
        printf("Erro: pilha de escopos não inicializada\n");
        return;
    }
    Variavel *nova_variavel = (Variavel *)malloc(sizeof(Variavel));
    nova_variavel->tipo = strdup(tipo);
    nova_variavel->nome = strdup(nome);
    nova_variavel->tipo_valor = TIPO_CADEIA;
    nova_variavel->valor.str_valor = strdup(str_valor);

    nova_variavel->tipo_linha = tipo_linha;

    nova_variavel->proximo = pilha_de_escopos->variaveis;
    pilha_de_escopos->variaveis = nova_variavel;
}

void atualiza_variavel(char *tipo, char *nome, int num_valor, char *str_valor, char *tipo_linha) {
    Escopo *escopo_atual = pilha_de_escopos;
    while (escopo_atual != NULL) {
        Variavel *var_atual = escopo_atual->variaveis;
        while (var_atual != NULL) {
            if (strcmp(var_atual->nome, nome) == 0) {

                // Atualiza os valores conforme o tipo
                if (strcmp(tipo, "NUMERO") == 0) {
                    var_atual->tipo_valor = TIPO_NUMERO;
                    var_atual->valor.num_valor = num_valor;
                } else if (strcmp(tipo, "CADEIA") == 0) {
                    var_atual->tipo_valor = TIPO_CADEIA;
                    if (strcmp(var_atual->tipo, "CADEIA") == 0) {
                        free(var_atual->valor.str_valor);
                    }
                    var_atual->valor.str_valor = strdup(str_valor);
                }
                // Atualiza o tipo da variável
                free(var_atual->tipo);
                var_atual->tipo = strdup(tipo);
                // Atualiza o campo tipo_linha
                var_atual->tipo_linha = strdup(tipo_linha);
                return;
            }
            var_atual = var_atual->proximo;
        }
        escopo_atual = escopo_atual->proximo;
    }
    printf("Erro: variável %s não encontrada.\n", nome);
}

void imprimir_pilha() {
    printf("Pilha = [");
    Escopo *escopo_atual = pilha_de_escopos;
    while (escopo_atual != NULL) {
        printf("[");
        Variavel *var_atual = escopo_atual->variaveis;
        while (var_atual != NULL) {
            if (var_atual->tipo_valor == TIPO_NUMERO) {
                printf("[%s, %s, %d, %s]", var_atual->tipo, var_atual->nome, var_atual->valor.num_valor, var_atual->tipo_linha);
            } else {
                printf("[%s, %s, %s, %s]", var_atual->tipo, var_atual->nome, var_atual->valor.str_valor, var_atual->tipo_linha);
            }
            var_atual = var_atual->proximo;
            if (var_atual != NULL) {
                printf(", ");
            }
        }
        printf("]");
        escopo_atual = escopo_atual->proximo;
        if (escopo_atual != NULL) {
            printf(", ");
        }
    }
    printf("]\n");
}

char* numero_para_string(int numero) {
    // Aloca memória para armazenar a string resultante
    // Assumindo que o número não terá mais de 50 caracteres
    char *buffer = (char *)malloc(50 * sizeof(char));
    if (buffer != NULL) {
        sprintf(buffer, "%d", numero);
    }
    return buffer;
}

int regex_match(char *str, char *pattern) {
    regex_t regex;
    int reti;

    // Compila a expressão regular
    reti = regcomp(&regex, pattern, REG_EXTENDED);
    if (reti) {
        fprintf(stderr, "Não foi possível compilar a expressão regular\n");
        return 0;
    }

    // Executa a correspondência da expressão regular
    reti = regexec(&regex, str, 0, NULL, 0);
    regfree(&regex);

    // Retorna 1 se corresponder, 0 caso contrário
    return !reti;
}

char* verificar_tipo(char *str) {
    // Expressão regular para números
    char *numero_regex = "^[+-]?[0-9]+(\\.[0-9]+)?$";
    // Expressão regular para cadeias
    char *cadeia_regex = "^\"([^\"]*)\"$";

    if (regex_match(str, numero_regex)) {
        return "NUMERO";
    } else if (regex_match(str, cadeia_regex)) {
        return "CADEIA";
    } else {
        return "DESCONHECIDO";
    }
}

char* retira_ultimo_digito(char *str) {
    size_t len = strlen(str); // Obter o comprimento da string

    if (len == 0) {
        return NULL; // Retornar NULL se a string estiver vazia
    }

    // Alocar memória para a nova string, excluindo o último caractere (a aspas de fechamento)
    char *nova_str = (char *)malloc(len * sizeof(char));
    if (nova_str == NULL) {
        fprintf(stderr, "Erro ao alocar memória\n");
        return NULL;
    }

    // Copiar a string original para a nova string, excluindo o último caractere
    strncpy(nova_str, str, len - 1);
    nova_str[len - 1] = '\0'; // Adicionar o caractere nulo terminador

    return nova_str;
}

char* retira_primeiro_digito(char *str) {
    size_t len = strlen(str); // Obter o comprimento da string

    if (len <= 1) {
        return NULL; // Retornar NULL se a string estiver vazia ou tiver apenas um caractere
    }

    // Alocar memória para a nova string, excluindo o primeiro caractere (a aspas de abertura)
    char *nova_str = (char *)malloc(len * sizeof(char));
    if (nova_str == NULL) {
        fprintf(stderr, "Erro ao alocar memória\n");
        return NULL;
    }

    // Copiar a string original para a nova string, excluindo o primeiro caractere
    strcpy(nova_str, str + 1);

    return nova_str;
}

int linha_indice = 0; // Declaração da variável de contagem de linhas


#line 387 "teste.y"
typedef union 
{
	int number;
    char *string;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	BLOCO_INICIO	258
#define	BLOCO_FIM	259
#define	IDENTIFICADOR	260
#define	CADEIA	261
#define	NUMERO	262
#define	TIPO_NUMERO	263
#define	TIPO_CADEIA	264
#define	PRINT	265


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int BLOCO_INICIO;
static const int BLOCO_FIM;
static const int IDENTIFICADOR;
static const int CADEIA;
static const int NUMERO;
static const int TIPO_NUMERO;
static const int TIPO_CADEIA;
static const int PRINT;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,BLOCO_INICIO=258
	,BLOCO_FIM=259
	,IDENTIFICADOR=260
	,CADEIA=261
	,NUMERO=262
	,TIPO_NUMERO=263
	,TIPO_CADEIA=264
	,PRINT=265


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::BLOCO_INICIO=258;
const int YY_parse_CLASS::BLOCO_FIM=259;
const int YY_parse_CLASS::IDENTIFICADOR=260;
const int YY_parse_CLASS::CADEIA=261;
const int YY_parse_CLASS::NUMERO=262;
const int YY_parse_CLASS::TIPO_NUMERO=263;
const int YY_parse_CLASS::TIPO_CADEIA=264;
const int YY_parse_CLASS::PRINT=265;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		52
#define	YYFLAG		-32768
#define	YYNTBASE	15

#define YYTRANSLATE(x) ((unsigned)(x) <= 265 ? yytranslate[x] : 29)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    14,    12,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    11,     2,
    13,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     4,     6,     8,    11,    14,    17,    18,    20,
    22,    25,    28,    30,    34,    38,    40,    42,    44,    48,
    52,    54,    58,    62,    64,    66,    68,    72,    76,    80,
    82,    84,    86,    90,    94,    98
};

static const short yyrhs[] = {    15,
    16,     0,     0,    17,     0,    18,     0,    19,    11,     0,
    26,    11,     0,    28,    11,     0,     0,     3,     0,     4,
     0,     9,    20,     0,     8,    23,     0,    21,     0,    20,
    12,    21,     0,     5,    13,    22,     0,     5,     0,     6,
     0,     5,     0,    22,    14,     6,     0,    22,    14,     5,
     0,    24,     0,    23,    12,    24,     0,     5,    13,    25,
     0,     5,     0,     7,     0,     5,     0,    25,    14,     7,
     0,    25,    14,     5,     0,     5,    13,    27,     0,     7,
     0,     6,     0,     5,     0,    27,    14,     7,     0,    27,
    14,     6,     0,    27,    14,     5,     0,    10,     5,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   399,   401,   404,   406,   407,   408,   409,   410,   413,   419,
   425,   427,   430,   432,   434,   454,   474,   479,   490,   503,
   529,   531,   533,   553,   573,   577,   589,   592,   611,   652,
   656,   660,   680,   689,   709,   745
};

static const char * const yytname[] = {   "$","error","$illegal.","BLOCO_INICIO",
"BLOCO_FIM","IDENTIFICADOR","CADEIA","NUMERO","TIPO_NUMERO","TIPO_CADEIA","PRINT",
"';'","','","'='","'+'","programa","linha","linha_inicio_bloco","linha_fim_bloco",
"linha_declaracao","lista_declaracao_cadeia","declaracao_cadeia","expressao_cadeia",
"lista_declaracao_numero","declaracao_numero","expressao_numero","linha_atribuicao",
"expressao","linha_print",""
};
#endif

static const short yyr1[] = {     0,
    15,    15,    16,    16,    16,    16,    16,    16,    17,    18,
    19,    19,    20,    20,    21,    21,    22,    22,    22,    22,
    23,    23,    24,    24,    25,    25,    25,    25,    26,    27,
    27,    27,    27,    27,    27,    28
};

static const short yyr2[] = {     0,
     2,     0,     1,     1,     2,     2,     2,     0,     1,     1,
     2,     2,     1,     3,     3,     1,     1,     1,     3,     3,
     1,     3,     3,     1,     1,     1,     3,     3,     3,     1,
     1,     1,     3,     3,     3,     2
};

static const short yydefact[] = {     2,
     0,     9,    10,     0,     0,     0,     0,     1,     3,     4,
     0,     0,     0,     0,    24,    12,    21,    16,    11,    13,
    36,     5,     6,     7,    32,    31,    30,    29,     0,     0,
     0,     0,     0,    26,    25,    23,    22,    18,    17,    15,
    14,    35,    34,    33,     0,     0,    28,    27,    20,    19,
     0,     0
};

static const short yydefgoto[] = {     1,
     8,     9,    10,    11,    19,    20,    40,    16,    17,    36,
    12,    28,    13
};

static const short yypact[] = {-32768,
     0,-32768,-32768,     8,    17,    18,    19,-32768,-32768,-32768,
    14,    15,    16,     6,    20,    22,-32768,    23,    25,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    21,    12,    17,
    -4,    18,     9,-32768,-32768,    24,-32768,-32768,-32768,    26,
-32768,-32768,-32768,-32768,    13,     1,-32768,-32768,-32768,-32768,
    28,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,-32768,-32768,-32768,    -3,-32768,-32768,     2,-32768,
-32768,-32768,-32768
};


#define	YYLAST		40


static const short yytable[] = {    51,
    38,    39,     2,     3,     4,    49,    50,     5,     6,     7,
    25,    26,    27,    42,    43,    44,    34,    47,    35,    48,
    14,    15,    18,    21,    22,    23,    24,    52,    41,     0,
     0,    37,    29,    30,    33,    31,    32,    45,     0,    46
};

static const short yycheck[] = {     0,
     5,     6,     3,     4,     5,     5,     6,     8,     9,    10,
     5,     6,     7,     5,     6,     7,     5,     5,     7,     7,
    13,     5,     5,     5,    11,    11,    11,     0,    32,    -1,
    -1,    30,    13,    12,    14,    13,    12,    14,    -1,    14
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 400 "teste.y"
{linha_indice++; /*printf("[%d] ", linha_indice); imprimir_pilha();*/;
    break;}
case 9:
#line 414 "teste.y"
{
        empilhar_escopo();
    ;
    break;}
case 10:
#line 420 "teste.y"
{
        desempilhar_escopo();
    ;
    break;}
case 15:
#line 435 "teste.y"
{ 
        char* s1 = remove_espacos(yyvsp[-2].string);
        if (verifica_variavel_existe_pilha(s1) == NULL) {
            adicionar_variavel_cadeia("CADEIA", s1, yyvsp[0].string, "linha_declaracao");
        }
        else {
            if (verifica_variavel_existe_escopo_atual(s1) == NULL){
                    adicionar_variavel_cadeia("CADEIA", s1, yyvsp[0].string, "linha_declaracao");
            }
            else {
                if(strcmp(buscar_tipo_linha(s1), "linha_atribuicao") == 0){
                    atualiza_variavel("CADEIA", s1, 0, yyvsp[0].string, "linha_declaracao");
                }
                else{
                    printf("[%d] Erro: variável '%s' já declarada no escopo\n", linha_indice, s1);
                }
            }
        }
    ;
    break;}
case 16:
#line 454 "teste.y"
{
        char* s1 = remove_espacos(yyvsp[0].string); 
        if (verifica_variavel_existe_pilha(remove_espacos(s1)) == NULL) {
            adicionar_variavel_cadeia("CADEIA", s1, "", "linha_declaracao");
        }
        else {
            if (verifica_variavel_existe_escopo_atual(s1) == NULL){
                    adicionar_variavel_cadeia("CADEIA", s1, "", "linha_declaracao");
            }
            else {
                if(strcmp(buscar_tipo_linha(s1), "linha_atribuicao") == 0){
                    atualiza_variavel("CADEIA", s1, 0, "", "linha_declaracao");
                }
                else{
                    printf("[%d] Erro: variável '%s' já declarada no escopo\n", linha_indice, s1);
                }
            }
        }
    ;
    break;}
case 17:
#line 475 "teste.y"
{ 
        char* s1 = remove_espacos_fora_aspas(yyvsp[0].string);
        yyval.string = s1;
    ;
    break;}
case 18:
#line 479 "teste.y"
{ 
        char* s1 = remove_espacos(yyvsp[0].string);
        if(verifica_variavel_existe_pilha(s1) != NULL){
            if(strcmp(verifica_tipo_variavel(s1), "CADEIA") == 0){
                yyval.string = busca_valor_variavel_cadeia(s1); 
            }
            else{
                printf("[%d] Erro: tipos não compatíveis\n", linha_indice);
            }
        }
    ;
    break;}
case 19:
#line 490 "teste.y"
{
        char* s1 = retira_ultimo_digito(yyvsp[-2].string);
        char* s3 = remove_espacos_fora_aspas(yyvsp[0].string);
        s3 = retira_primeiro_digito(s3);
        size_t len1 = strlen(s1);
        size_t len2 = strlen(s3);
        char* result = (char*)malloc(len1 + len2 + 1);

        strcpy(result, s1);
        strcat(result, s3);

        yyval.string  = result;
    ;
    break;}
case 20:
#line 503 "teste.y"
{
        char* s3 = remove_espacos(yyvsp[0].string);
        if(verifica_variavel_existe_pilha(s3) != NULL){
            if(strcmp(verifica_tipo_variavel(s3), "CADEIA") == 0){
                char* s1 = retira_ultimo_digito(yyvsp[-2].string);
                char* valor_variavel_s3 = busca_valor_variavel_cadeia(s3);
                valor_variavel_s3 = retira_primeiro_digito(valor_variavel_s3);

                size_t len1 = strlen(s1);
                size_t len2 = strlen(valor_variavel_s3);
                char* result = (char*)malloc(len1 + len2 + 1);

                strcpy(result, s1);
                strcat(result, valor_variavel_s3);

                yyval.string  = result;
            }
            else{
                printf("[%d] Erro: tipos não compatíveis\n", linha_indice);
            }
        }
        else{
            printf("[%d] Erro: variável não declarada\n", linha_indice);
        }
    ;
    break;}
case 23:
#line 534 "teste.y"
{ 
        char* s1 = remove_espacos(yyvsp[-2].string);
        if (verifica_variavel_existe_pilha(s1) == NULL) {
            adicionar_variavel_numero("NUMERO", s1, yyvsp[0].number, "linha_declaracao");
        }
        else {
            if (verifica_variavel_existe_escopo_atual(s1) == NULL){
                adicionar_variavel_numero("NUMERO", s1, yyvsp[0].number, "linha_declaracao");
            }
            else {
                if(strcmp(buscar_tipo_linha(s1), "linha_atribuicao") == 0){
                    atualiza_variavel("NUMERO", s1, yyvsp[0].number, "", "linha_declaracao");
                }
                else{
                    printf("[%d] Erro: variável '%s' já declarada no escopo\n", linha_indice, s1);
                }
            }
        }
    ;
    break;}
case 24:
#line 553 "teste.y"
{
        char* s1 = remove_espacos(yyvsp[0].string); 
        if (verifica_variavel_existe_pilha(remove_espacos(s1)) == NULL) {
            adicionar_variavel_numero("NUMERO", s1, 0, "linha_declaracao");
        }
        else {
            if (verifica_variavel_existe_escopo_atual(s1) == NULL){
                adicionar_variavel_numero("NUMERO", s1, 0, "linha_declaracao");
            }
            else {
                if(strcmp(buscar_tipo_linha(s1), "linha_atribuicao") == 0){
                    atualiza_variavel("NUMERO", s1, 0, "", "linha_declaracao");
                }
                else{
                    printf("[%d] Erro: variável '%s' já declarada no escopo\n", linha_indice, s1);
                }
            }
        }
    ;
    break;}
case 25:
#line 574 "teste.y"
{ 
        yyval.number = yyvsp[0].number; 
    ;
    break;}
case 26:
#line 577 "teste.y"
{ 
        char* s1 = remove_espacos(yyvsp[0].string);
        if(verifica_variavel_existe_pilha(s1) != NULL){
            if(strcmp(verifica_tipo_variavel(s1), "NUMERO") == 0){
                yyval.number = busca_valor_variavel_numero(s1); 
            }
            else{
                //$$.string = busca_valor_variavel_numero(s1); 
                printf("[%d] Erro: tipos não compatíveis\n", linha_indice);
            }
        }
    ;
    break;}
case 27:
#line 589 "teste.y"
{ 
        yyval.number  = yyvsp[-2].number + yyvsp[0].number; 
    ;
    break;}
case 28:
#line 592 "teste.y"
{
        char* s3 = remove_espacos(yyvsp[0].string);
        if(verifica_variavel_existe_pilha(s3) != NULL){
            if(strcmp(verifica_tipo_variavel(s3), "NUMERO") == 0){
                int valor_variavel_s3 = busca_valor_variavel_numero(s3);
                yyval.number  = yyvsp[-2].number + valor_variavel_s3; 
            }
            else{
                //char* valor_variavel_s3 = busca_valor_variavel_numero(s3);
                //$$.string  = $1.number + valor_variavel_s3; 
                printf("[%d] Erro: tipos não compatíveis\n", linha_indice);
            }
        }
        else{
            printf("[%d] Erro: variável não declarada\n", linha_indice);
        }
    ;
    break;}
case 29:
#line 612 "teste.y"
{
        char* tipo_expressao = verificar_tipo(yyvsp[0].string);
        char* s1 = remove_espacos(yyvsp[-2].string);
        if (verifica_variavel_existe_pilha(s1) != NULL) {
            char* tipo_variavel = verifica_tipo_variavel(s1);
            tipo_expressao = verificar_tipo(yyvsp[0].string);
            if (strcmp(tipo_variavel, tipo_expressao) == 0) {
                if (verifica_variavel_existe_escopo_atual(s1) == NULL){
                    if (strcmp(tipo_expressao, "NUMERO") == 0){
                        int expressao_number = atoi(yyvsp[0].string);
                        adicionar_variavel_numero("NUMERO", s1, expressao_number, "linha_atribuicao");
                    }
                    else if (strcmp(tipo_expressao, "CADEIA") == 0){
                        adicionar_variavel_cadeia("CADEIA", s1, yyvsp[0].string, "linha_atribuicao");
                    }
                }
                else {
                    if (strcmp(tipo_expressao, "NUMERO") == 0){
                        int expressao_number = atoi(yyvsp[0].string);
                        atualiza_variavel("NUMERO", s1, expressao_number, "", "linha_declaracao");
                    }
                    else if (strcmp(tipo_expressao, "CADEIA") == 0){
                        char* nova_cadeia;
                        nova_cadeia = (char *)malloc((strlen(yyvsp[0].string) + 1) * sizeof(char));
                        strcpy(nova_cadeia, yyvsp[0].string);
                        atualiza_variavel("CADEIA", s1, 0, nova_cadeia, "linha_declaracao");
                        free(nova_cadeia);
                    }
                    else{
                        printf("[%d] Erro: tipo inválido\n", linha_indice);
                    }
                }
            }
            else {
                printf("[%d] Erro: tipos não compatíveis\n", linha_indice);
            }
        } else {
            printf("[%d] Erro: variável '%s' não declarada\n", linha_indice, s1);
        }
    ;
    break;}
case 30:
#line 653 "teste.y"
{
        yyval.string = numero_para_string(yyvsp[0].number);
    ;
    break;}
case 31:
#line 656 "teste.y"
{
        char* s1 = remove_espacos_fora_aspas(yyvsp[0].string);
        yyval.string = s1;
    ;
    break;}
case 32:
#line 660 "teste.y"
{
        char* s1 = remove_espacos(yyvsp[0].string);
        if (verifica_variavel_existe_pilha(s1) != NULL) {
            char* tipo_variavel = verifica_tipo_variavel(s1);
            if(strcmp(tipo_variavel, "NUMERO") == 0){
                int valor_variavel_s1 = busca_valor_variavel_numero(s1);
                yyval.string = numero_para_string(valor_variavel_s1);
            }
            else if(strcmp(tipo_variavel, "CADEIA") == 0){
                char* valor_variavel_s1 = busca_valor_variavel_cadeia(s1);
                yyval.string = valor_variavel_s1;
            }
            else {
                printf("[%d] Erro: variável '%s' com tipo inválido\n", linha_indice, s1);
            }
        } 
        else {
            printf("[%d] Erro: variável '%s' não declarada\n", linha_indice, s1);
        }
    ;
    break;}
case 33:
#line 680 "teste.y"
{
        char* tipo_expressao = verificar_tipo(yyvsp[-2].string);
        if (strcmp(tipo_expressao, "NUMERO") == 0 ) {
            int soma = atoi(yyvsp[-2].string) + yyvsp[0].number;
            yyval.string = numero_para_string(soma);
        } else {
           printf("[%d] Erro: Tipos incompatíveis\n", linha_indice);
        }
    ;
    break;}
case 34:
#line 689 "teste.y"
{
        char* tipo_expressao = verificar_tipo(yyvsp[-2].string);
        if (strcmp(tipo_expressao, "CADEIA") == 0) {
            char* s1 = retira_ultimo_digito(yyvsp[-2].string);
            char* s3 = remove_espacos_fora_aspas(yyvsp[0].string);
            s3 = retira_primeiro_digito(s3);

            size_t len1 = strlen(s1);
            size_t len2 = strlen(s3);
            char* result = (char*)malloc(len1 + len2 + 1);

            strcpy(result, s1);
            strcat(result, s3);

            yyval.string  = result;
        } 
        else {
           printf("[%d] Erro: Tipos incompatíveis\n", linha_indice);
        }
    ;
    break;}
case 35:
#line 709 "teste.y"
{
        char* tipo_expressao = verificar_tipo(yyvsp[-2].string);
        char* s3 = remove_espacos(yyvsp[0].string);
        if (verifica_variavel_existe_pilha(s3) != NULL) {
            char* tipo_variavel = verifica_tipo_variavel(s3);
            if (strcmp(tipo_expressao, tipo_variavel) == 0){
                if (strcmp(tipo_expressao, "NUMERO") == 0) {
                    int valor_variavel_s3 = busca_valor_variavel_numero(s3);
                    int soma = atoi(yyvsp[-2].string) + valor_variavel_s3;
                    yyval.string = numero_para_string(soma);
                }
                else if (strcmp(tipo_expressao, "CADEIA") == 0){
                    char* s1 = retira_ultimo_digito(yyvsp[-2].string);
                    char* valor_variavel_s3 = busca_valor_variavel_cadeia(s3);
                    valor_variavel_s3 = retira_primeiro_digito(valor_variavel_s3);

                    size_t len1 = strlen(s1);
                    size_t len2 = strlen(valor_variavel_s3);
                    char* result = (char*)malloc(len1 + len2 + 1);

                    strcpy(result, s1);
                    strcat(result, valor_variavel_s3);

                    yyval.string  = result;
                }
            }
            else {
                printf("[%d] Erro: tipos não compatíveis\n", linha_indice);
            }
        }
        else {
            printf("[%d] Erro: variável '%s' não declarada\n", linha_indice, s3);
        }

    ;
    break;}
case 36:
#line 746 "teste.y"
{ 
        char* s2 = remove_espacos(yyvsp[0].string);

        if(verifica_variavel_existe_pilha(s2) != NULL){
            if(strcmp(verifica_tipo_variavel(s2), "NUMERO") == 0){
                printf("[%d] %d\n", linha_indice, busca_valor_variavel_numero(s2));
            }
            else{
                printf("[%d] %s\n", linha_indice, busca_valor_variavel_cadeia(s2));
            }
        }
        else {
            printf("[%d] Erro: variável não declarada\n", linha_indice);
        }
    ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 763 "teste.y"


void yyerror(const char *s) {
    fprintf(stderr, "Erro: %s\n", s);
}

int main(void) {
    inicializar_pilha_de_escopos();
    return yyparse();
}